# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImportCsvDialog.ui',
# licensing of 'ImportCsvDialog.ui' applies.
#
# Created: Wed May 22 21:22:44 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ImportCsvDialog(object):
    def setupUi(self, ImportCsvDialog):
        ImportCsvDialog.setObjectName("ImportCsvDialog")
        ImportCsvDialog.resize(620, 360)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../ico/appicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ImportCsvDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(ImportCsvDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_tableName = QtWidgets.QLineEdit(ImportCsvDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_tableName.sizePolicy().hasHeightForWidth())
        self.lineEdit_tableName.setSizePolicy(sizePolicy)
        self.lineEdit_tableName.setAcceptDrops(False)
        self.lineEdit_tableName.setObjectName("lineEdit_tableName")
        self.gridLayout.addWidget(self.lineEdit_tableName, 1, 0, 1, 1)
        self.label_deckName = QtWidgets.QLabel(ImportCsvDialog)
        self.label_deckName.setObjectName("label_deckName")
        self.gridLayout.addWidget(self.label_deckName, 0, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox_vocabulary = QtWidgets.QComboBox(ImportCsvDialog)
        self.comboBox_vocabulary.setObjectName("comboBox_vocabulary")
        self.gridLayout_2.addWidget(self.comboBox_vocabulary, 1, 0, 1, 1)
        self.comboBox_definition = QtWidgets.QComboBox(ImportCsvDialog)
        self.comboBox_definition.setObjectName("comboBox_definition")
        self.gridLayout_2.addWidget(self.comboBox_definition, 1, 1, 1, 1)
        self.comboBox_separator = QtWidgets.QComboBox(ImportCsvDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_separator.sizePolicy().hasHeightForWidth())
        self.comboBox_separator.setSizePolicy(sizePolicy)
        self.comboBox_separator.setFrame(True)
        self.comboBox_separator.setObjectName("comboBox_separator")
        self.comboBox_separator.addItem("")
        self.comboBox_separator.addItem("")
        self.comboBox_separator.addItem("")
        self.comboBox_separator.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_separator, 1, 2, 1, 1)
        self.label_vocabulary = QtWidgets.QLabel(ImportCsvDialog)
        self.label_vocabulary.setObjectName("label_vocabulary")
        self.gridLayout_2.addWidget(self.label_vocabulary, 0, 0, 1, 1)
        self.label_definition = QtWidgets.QLabel(ImportCsvDialog)
        self.label_definition.setObjectName("label_definition")
        self.gridLayout_2.addWidget(self.label_definition, 0, 1, 1, 1)
        self.label_separator = QtWidgets.QLabel(ImportCsvDialog)
        self.label_separator.setObjectName("label_separator")
        self.gridLayout_2.addWidget(self.label_separator, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.plainTextEdit_deckName = QtWidgets.QPlainTextEdit(ImportCsvDialog)
        self.plainTextEdit_deckName.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.plainTextEdit_deckName.setTabChangesFocus(True)
        self.plainTextEdit_deckName.setObjectName("plainTextEdit_deckName")
        self.verticalLayout.addWidget(self.plainTextEdit_deckName)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_numLines = QtWidgets.QLabel(ImportCsvDialog)
        self.label_numLines.setText("")
        self.label_numLines.setObjectName("label_numLines")
        self.horizontalLayout_4.addWidget(self.label_numLines)
        self.buttonBox = QtWidgets.QDialogButtonBox(ImportCsvDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(ImportCsvDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ImportCsvDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ImportCsvDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ImportCsvDialog)

    def retranslateUi(self, ImportCsvDialog):
        ImportCsvDialog.setWindowTitle(QtWidgets.QApplication.translate("ImportCsvDialog", "Import from CSV", None, -1))
        self.lineEdit_tableName.setPlaceholderText(QtWidgets.QApplication.translate("ImportCsvDialog", "Name of new deck", None, -1))
        self.label_deckName.setText(QtWidgets.QApplication.translate("ImportCsvDialog", "Deck name", None, -1))
        self.comboBox_separator.setItemText(0, QtWidgets.QApplication.translate("ImportCsvDialog", ",", None, -1))
        self.comboBox_separator.setItemText(1, QtWidgets.QApplication.translate("ImportCsvDialog", "tab", None, -1))
        self.comboBox_separator.setItemText(2, QtWidgets.QApplication.translate("ImportCsvDialog", "-", None, -1))
        self.comboBox_separator.setItemText(3, QtWidgets.QApplication.translate("ImportCsvDialog", "/", None, -1))
        self.label_vocabulary.setText(QtWidgets.QApplication.translate("ImportCsvDialog", "Vocabulary", None, -1))
        self.label_definition.setText(QtWidgets.QApplication.translate("ImportCsvDialog", "Definition", None, -1))
        self.label_separator.setText(QtWidgets.QApplication.translate("ImportCsvDialog", "Separator", None, -1))
        self.plainTextEdit_deckName.setPlaceholderText(QtWidgets.QApplication.translate("ImportCsvDialog", "Vocabulary,Definition,Pronunciation(optional)", None, -1))

