# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowView.ui',
# licensing of 'MainWindowView.ui' applies.
#
# Created: Thu Jun 20 16:27:05 2019
#      by: pyside2-uic  running on PySide2 5.12.4
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1249, 627)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(900, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../.designer/ico/appicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(600, 400))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabBar = QtWidgets.QTabBar()
        self.tabWidget.setTabBar(self.tabBar)
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(900, 0))
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_wordTable = QtWidgets.QWidget()
        self.tab_wordTable.setObjectName("tab_wordTable")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_wordTable)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_shuffleDeck = QtWidgets.QPushButton(self.tab_wordTable)
        self.pushButton_shuffleDeck.setObjectName("pushButton_shuffleDeck")
        self.horizontalLayout_12.addWidget(self.pushButton_shuffleDeck)
        self.checkBox_starredOnly = QtWidgets.QCheckBox(self.tab_wordTable)
        self.checkBox_starredOnly.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_starredOnly.setObjectName("checkBox_starredOnly")
        self.horizontalLayout_12.addWidget(self.checkBox_starredOnly)
        self.gridLayout.addLayout(self.horizontalLayout_12, 5, 4, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit_searchQuery = QtWidgets.QLineEdit(self.tab_wordTable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_searchQuery.sizePolicy().hasHeightForWidth())
        self.lineEdit_searchQuery.setSizePolicy(sizePolicy)
        self.lineEdit_searchQuery.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEdit_searchQuery.setMaximumSize(QtCore.QSize(180, 32))
        self.lineEdit_searchQuery.setObjectName("lineEdit_searchQuery")
        self.horizontalLayout.addWidget(self.lineEdit_searchQuery)
        self.pushButton_search = QtWidgets.QPushButton(self.tab_wordTable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_search.sizePolicy().hasHeightForWidth())
        self.pushButton_search.setSizePolicy(sizePolicy)
        self.pushButton_search.setMaximumSize(QtCore.QSize(64, 32))
        self.pushButton_search.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_search.setObjectName("pushButton_search")
        self.horizontalLayout.addWidget(self.pushButton_search)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 6, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.toolButton_add = QtWidgets.QToolButton(self.tab_wordTable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_add.sizePolicy().hasHeightForWidth())
        self.toolButton_add.setSizePolicy(sizePolicy)
        self.toolButton_add.setMinimumSize(QtCore.QSize(0, 0))
        self.toolButton_add.setMaximumSize(QtCore.QSize(120, 32))
        self.toolButton_add.setCheckable(False)
        self.toolButton_add.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButton_add.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButton_add.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_add.setObjectName("toolButton_add")
        self.horizontalLayout_10.addWidget(self.toolButton_add)
        self.pushButton_wordList_select = QtWidgets.QPushButton(self.tab_wordTable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_wordList_select.sizePolicy().hasHeightForWidth())
        self.pushButton_wordList_select.setSizePolicy(sizePolicy)
        self.pushButton_wordList_select.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_wordList_select.setMaximumSize(QtCore.QSize(120, 32))
        self.pushButton_wordList_select.setObjectName("pushButton_wordList_select")
        self.horizontalLayout_10.addWidget(self.pushButton_wordList_select)
        self.gridLayout.addLayout(self.horizontalLayout_10, 5, 0, 1, 3)
        self.buttonBox_wordList = QtWidgets.QDialogButtonBox(self.tab_wordTable)
        self.buttonBox_wordList.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox_wordList.sizePolicy().hasHeightForWidth())
        self.buttonBox_wordList.setSizePolicy(sizePolicy)
        self.buttonBox_wordList.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonBox_wordList.setMaximumSize(QtCore.QSize(16777215, 32))
        self.buttonBox_wordList.setBaseSize(QtCore.QSize(0, 0))
        self.buttonBox_wordList.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox_wordList.setCenterButtons(False)
        self.buttonBox_wordList.setObjectName("buttonBox_wordList")
        self.gridLayout.addWidget(self.buttonBox_wordList, 5, 6, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_deckList = QtWidgets.QLabel(self.tab_wordTable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_deckList.sizePolicy().hasHeightForWidth())
        self.label_deckList.setSizePolicy(sizePolicy)
        self.label_deckList.setMinimumSize(QtCore.QSize(0, 35))
        self.label_deckList.setMaximumSize(QtCore.QSize(16777215, 41))
        self.label_deckList.setAlignment(QtCore.Qt.AlignCenter)
        self.label_deckList.setObjectName("label_deckList")
        self.horizontalLayout_3.addWidget(self.label_deckList)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 3)
        self.deckList = QtWidgets.QListWidget(self.tab_wordTable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deckList.sizePolicy().hasHeightForWidth())
        self.deckList.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.deckList.setFont(font)
        self.deckList.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.deckList.setAutoScrollMargin(16)
        self.deckList.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.deckList.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.deckList.setAlternatingRowColors(True)
        self.deckList.setMovement(QtWidgets.QListView.Free)
        self.deckList.setResizeMode(QtWidgets.QListView.Adjust)
        self.deckList.setObjectName("deckList")
        QtWidgets.QListWidgetItem(self.deckList)
        self.gridLayout.addWidget(self.deckList, 4, 0, 1, 3)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_selectedDeck = QtWidgets.QLabel(self.tab_wordTable)
        self.label_selectedDeck.setMinimumSize(QtCore.QSize(34, 0))
        self.label_selectedDeck.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_selectedDeck.setObjectName("label_selectedDeck")
        self.verticalLayout_12.addWidget(self.label_selectedDeck)
        self.gridLayout.addLayout(self.verticalLayout_12, 0, 5, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_avgScore = QtWidgets.QLabel(self.tab_wordTable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_avgScore.sizePolicy().hasHeightForWidth())
        self.label_avgScore.setSizePolicy(sizePolicy)
        self.label_avgScore.setObjectName("label_avgScore")
        self.verticalLayout_5.addWidget(self.label_avgScore)
        self.label_lastStudied = QtWidgets.QLabel(self.tab_wordTable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_lastStudied.sizePolicy().hasHeightForWidth())
        self.label_lastStudied.setSizePolicy(sizePolicy)
        self.label_lastStudied.setObjectName("label_lastStudied")
        self.verticalLayout_5.addWidget(self.label_lastStudied)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 4, 1, 1)
        self.tableView = QtWidgets.QTableView(self.tab_wordTable)
        self.tableView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 4, 4, 1, 3)
        self.tabWidget.addTab(self.tab_wordTable, "")
        self.tab_typing = QtWidgets.QWidget()
        self.tab_typing.setObjectName("tab_typing")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_typing)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem3)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_typingAttempted = QtWidgets.QLabel(self.tab_typing)
        self.label_typingAttempted.setEnabled(True)
        self.label_typingAttempted.setObjectName("label_typingAttempted")
        self.verticalLayout_18.addWidget(self.label_typingAttempted)
        self.label_typingMissed = QtWidgets.QLabel(self.tab_typing)
        self.label_typingMissed.setObjectName("label_typingMissed")
        self.verticalLayout_18.addWidget(self.label_typingMissed)
        self.horizontalLayout_14.addLayout(self.verticalLayout_18)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.label_typingWord = QtWidgets.QLabel(self.tab_typing)
        font = QtGui.QFont()
        font.setFamily("WenQuanYi Zen Hei Mono")
        font.setPointSize(36)
        self.label_typingWord.setFont(font)
        self.label_typingWord.setWordWrap(True)
        self.label_typingWord.setObjectName("label_typingWord")
        self.horizontalLayout_5.addWidget(self.label_typingWord)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem7)
        self.progressBar_typing = QtWidgets.QProgressBar(self.tab_typing)
        self.progressBar_typing.setProperty("value", 24)
        self.progressBar_typing.setObjectName("progressBar_typing")
        self.verticalLayout_7.addWidget(self.progressBar_typing)
        self.line_2 = QtWidgets.QFrame(self.tab_typing)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_7.addWidget(self.line_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.lineEdit_answer = QtWidgets.QLineEdit(self.tab_typing)
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK JP")
        font.setPointSize(10)
        self.lineEdit_answer.setFont(font)
        self.lineEdit_answer.setText("")
        self.lineEdit_answer.setObjectName("lineEdit_answer")
        self.verticalLayout_17.addWidget(self.lineEdit_answer)
        self.horizontalLayout_6.addLayout(self.verticalLayout_17)
        self.pushButton_enter = QtWidgets.QPushButton(self.tab_typing)
        self.pushButton_enter.setAutoDefault(False)
        self.pushButton_enter.setDefault(True)
        self.pushButton_enter.setObjectName("pushButton_enter")
        self.horizontalLayout_6.addWidget(self.pushButton_enter)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_fractionCorrect = QtWidgets.QLabel(self.tab_typing)
        self.label_fractionCorrect.setEnabled(True)
        self.label_fractionCorrect.setTextFormat(QtCore.Qt.PlainText)
        self.label_fractionCorrect.setObjectName("label_fractionCorrect")
        self.horizontalLayout_7.addWidget(self.label_fractionCorrect)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.pushButton_notSure_Skip = QtWidgets.QPushButton(self.tab_typing)
        self.pushButton_notSure_Skip.setObjectName("pushButton_notSure_Skip")
        self.horizontalLayout_7.addWidget(self.pushButton_notSure_Skip)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.tab_typing, "")
        self.tab_flashcards = QtWidgets.QWidget()
        self.tab_flashcards.setObjectName("tab_flashcards")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_flashcards)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.label_flashWord = QtWidgets.QLabel(self.tab_flashcards)
        font = QtGui.QFont()
        font.setFamily("WenQuanYi Zen Hei Mono")
        font.setPointSize(36)
        self.label_flashWord.setFont(font)
        self.label_flashWord.setWordWrap(True)
        self.label_flashWord.setObjectName("label_flashWord")
        self.horizontalLayout_2.addWidget(self.label_flashWord)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem12)
        self.progressBar_flashcards = QtWidgets.QProgressBar(self.tab_flashcards)
        self.progressBar_flashcards.setProperty("value", 24)
        self.progressBar_flashcards.setObjectName("progressBar_flashcards")
        self.verticalLayout_6.addWidget(self.progressBar_flashcards)
        self.line_4 = QtWidgets.QFrame(self.tab_flashcards)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_6.addWidget(self.line_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_know = QtWidgets.QPushButton(self.tab_flashcards)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_know.sizePolicy().hasHeightForWidth())
        self.pushButton_know.setSizePolicy(sizePolicy)
        self.pushButton_know.setMinimumSize(QtCore.QSize(0, 64))
        self.pushButton_know.setObjectName("pushButton_know")
        self.horizontalLayout_4.addWidget(self.pushButton_know)
        self.pushButton_dontKnow = QtWidgets.QPushButton(self.tab_flashcards)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_dontKnow.sizePolicy().hasHeightForWidth())
        self.pushButton_dontKnow.setSizePolicy(sizePolicy)
        self.pushButton_dontKnow.setMinimumSize(QtCore.QSize(0, 64))
        self.pushButton_dontKnow.setObjectName("pushButton_dontKnow")
        self.horizontalLayout_4.addWidget(self.pushButton_dontKnow)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.checkBox_autoPlay = QtWidgets.QCheckBox(self.tab_flashcards)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_autoPlay.sizePolicy().hasHeightForWidth())
        self.checkBox_autoPlay.setSizePolicy(sizePolicy)
        self.checkBox_autoPlay.setObjectName("checkBox_autoPlay")
        self.verticalLayout_15.addWidget(self.checkBox_autoPlay)
        self.horizontalLayout_4.addLayout(self.verticalLayout_15)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tab_flashcards, "")
        self.tab_quiz = QtWidgets.QWidget()
        self.tab_quiz.setObjectName("tab_quiz")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tab_quiz)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem14)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem15)
        self.label_quizWord = QtWidgets.QLabel(self.tab_quiz)
        font = QtGui.QFont()
        font.setFamily("WenQuanYi Zen Hei Mono")
        font.setPointSize(36)
        self.label_quizWord.setFont(font)
        self.label_quizWord.setWordWrap(True)
        self.label_quizWord.setObjectName("label_quizWord")
        self.horizontalLayout_8.addWidget(self.label_quizWord)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem16)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem17)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.progressBar_quiz = QtWidgets.QProgressBar(self.tab_quiz)
        self.progressBar_quiz.setProperty("value", 24)
        self.progressBar_quiz.setObjectName("progressBar_quiz")
        self.verticalLayout_11.addWidget(self.progressBar_quiz)
        self.line_5 = QtWidgets.QFrame(self.tab_quiz)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_11.addWidget(self.line_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton_quizChoice1 = QtWidgets.QPushButton(self.tab_quiz)
        self.pushButton_quizChoice1.setMinimumSize(QtCore.QSize(0, 64))
        self.pushButton_quizChoice1.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton_quizChoice1.setObjectName("pushButton_quizChoice1")
        self.verticalLayout_9.addWidget(self.pushButton_quizChoice1)
        self.pushButton_quizChoice2 = QtWidgets.QPushButton(self.tab_quiz)
        self.pushButton_quizChoice2.setMinimumSize(QtCore.QSize(0, 64))
        self.pushButton_quizChoice2.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton_quizChoice2.setObjectName("pushButton_quizChoice2")
        self.verticalLayout_9.addWidget(self.pushButton_quizChoice2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_quizChoice3 = QtWidgets.QPushButton(self.tab_quiz)
        self.pushButton_quizChoice3.setMinimumSize(QtCore.QSize(0, 64))
        self.pushButton_quizChoice3.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton_quizChoice3.setObjectName("pushButton_quizChoice3")
        self.verticalLayout_10.addWidget(self.pushButton_quizChoice3)
        self.pushButton_quizChoice4 = QtWidgets.QPushButton(self.tab_quiz)
        self.pushButton_quizChoice4.setMinimumSize(QtCore.QSize(0, 64))
        self.pushButton_quizChoice4.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton_quizChoice4.setObjectName("pushButton_quizChoice4")
        self.verticalLayout_10.addWidget(self.pushButton_quizChoice4)
        self.horizontalLayout_9.addLayout(self.verticalLayout_10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11.addLayout(self.verticalLayout_11)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.verticalLayout_16.addLayout(self.verticalLayout_8)
        self.tabWidget.addTab(self.tab_quiz, "")
        self.tab_statistics = QtWidgets.QWidget()
        self.tab_statistics.setObjectName("tab_statistics")
        self.tabWidget.addTab(self.tab_statistics, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1249, 30))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuDeck = QtWidgets.QMenu(self.menubar)
        self.menuDeck.setObjectName("menuDeck")
        MainWindow.setMenuBar(self.menubar)
        self.actionFrom_Template = QtWidgets.QAction(MainWindow)
        self.actionFrom_Template.setObjectName("actionFrom_Template")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionTemplate_Data = QtWidgets.QAction(MainWindow)
        self.actionTemplate_Data.setObjectName("actionTemplate_Data")
        self.actionUser_Data = QtWidgets.QAction(MainWindow)
        self.actionUser_Data.setObjectName("actionUser_Data")
        self.actionImport_Data = QtWidgets.QAction(MainWindow)
        self.actionImport_Data.setObjectName("actionImport_Data")
        self.actionHow_to_play = QtWidgets.QAction(MainWindow)
        self.actionHow_to_play.setObjectName("actionHow_to_play")
        self.actionUserGuide = QtWidgets.QAction(MainWindow)
        self.actionUserGuide.setObjectName("actionUserGuide")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDonate = QtWidgets.QAction(MainWindow)
        self.actionDonate.setObjectName("actionDonate")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionBackup_Database = QtWidgets.QAction(MainWindow)
        self.actionBackup_Database.setObjectName("actionBackup_Database")
        self.actionExport_to_CSV = QtWidgets.QAction(MainWindow)
        self.actionExport_to_CSV.setObjectName("actionExport_to_CSV")
        self.actionSave_progress = QtWidgets.QAction(MainWindow)
        self.actionSave_progress.setObjectName("actionSave_progress")
        self.actionStar_current_word = QtWidgets.QAction(MainWindow)
        self.actionStar_current_word.setObjectName("actionStar_current_word")
        self.actionReset_Statistics = QtWidgets.QAction(MainWindow)
        self.actionReset_Statistics.setObjectName("actionReset_Statistics")
        self.actionRestore_Database = QtWidgets.QAction(MainWindow)
        self.actionRestore_Database.setObjectName("actionRestore_Database")
        self.actionToggle_Pronunciation = QtWidgets.QAction(MainWindow)
        self.actionToggle_Pronunciation.setCheckable(True)
        self.actionToggle_Pronunciation.setChecked(True)
        self.actionToggle_Pronunciation.setObjectName("actionToggle_Pronunciation")
        self.actionImport_from_CSV = QtWidgets.QAction(MainWindow)
        self.actionImport_from_CSV.setObjectName("actionImport_from_CSV")
        self.actionEdit_deck = QtWidgets.QAction(MainWindow)
        self.actionEdit_deck.setObjectName("actionEdit_deck")
        self.actionAdd_empty_deck = QtWidgets.QAction(MainWindow)
        self.actionAdd_empty_deck.setObjectName("actionAdd_empty_deck")
        self.menu_file.addAction(self.actionOpen)
        self.menu_file.addAction(self.actionSave_progress)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.actionQuit)
        self.menu_help.addAction(self.actionAbout)
        self.menu_help.addAction(self.actionDonate)
        self.menu_help.addAction(self.actionUserGuide)
        self.menuSettings.addAction(self.actionPreferences)
        self.menuSettings.addAction(self.actionBackup_Database)
        self.menuSettings.addAction(self.actionRestore_Database)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionReset_Statistics)
        self.menuView.addAction(self.actionToggle_Pronunciation)
        self.menuDeck.addAction(self.actionEdit_deck)
        self.menuDeck.addAction(self.actionAdd_empty_deck)
        self.menuDeck.addAction(self.actionImport_from_CSV)
        self.menuDeck.addAction(self.actionExport_to_CSV)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menuDeck.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.lineEdit_answer, QtCore.SIGNAL("returnPressed()"), self.pushButton_enter.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Vocab Trainer v0.5", None, -1))
        self.pushButton_shuffleDeck.setText(QtWidgets.QApplication.translate("MainWindow", "Shuffle Deck", None, -1))
        self.checkBox_starredOnly.setText(QtWidgets.QApplication.translate("MainWindow", "Study Starred Only", None, -1))
        self.lineEdit_searchQuery.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Search for a word", None, -1))
        self.pushButton_search.setText(QtWidgets.QApplication.translate("MainWindow", "Search", None, -1))
        self.toolButton_add.setText(QtWidgets.QApplication.translate("MainWindow", "Add Deck", None, -1))
        self.pushButton_wordList_select.setText(QtWidgets.QApplication.translate("MainWindow", "Select Deck", None, -1))
        self.label_deckList.setText(QtWidgets.QApplication.translate("MainWindow", "Deck List", None, -1))
        __sortingEnabled = self.deckList.isSortingEnabled()
        self.deckList.setSortingEnabled(False)
        self.deckList.item(0).setText(QtWidgets.QApplication.translate("MainWindow", "test", None, -1))
        self.deckList.setSortingEnabled(__sortingEnabled)
        self.label_selectedDeck.setText(QtWidgets.QApplication.translate("MainWindow", "Selected Deck: ", None, -1))
        self.label_avgScore.setText(QtWidgets.QApplication.translate("MainWindow", "Avg. Score: %0", None, -1))
        self.label_lastStudied.setText(QtWidgets.QApplication.translate("MainWindow", "Last Studied: Never", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_wordTable), QtWidgets.QApplication.translate("MainWindow", "Word List", None, -1))
        self.label_typingAttempted.setText(QtWidgets.QApplication.translate("MainWindow", "Times Attempted:", None, -1))
        self.label_typingMissed.setText(QtWidgets.QApplication.translate("MainWindow", "Times Missed:", None, -1))
        self.label_typingWord.setText(QtWidgets.QApplication.translate("MainWindow", "[null]", None, -1))
        self.lineEdit_answer.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Enter your answer", None, -1))
        self.pushButton_enter.setText(QtWidgets.QApplication.translate("MainWindow", "Enter", None, -1))
        self.label_fractionCorrect.setText(QtWidgets.QApplication.translate("MainWindow", "%0", None, -1))
        self.pushButton_notSure_Skip.setText(QtWidgets.QApplication.translate("MainWindow", "Not sure", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_typing), QtWidgets.QApplication.translate("MainWindow", "Typing", None, -1))
        self.label_flashWord.setText(QtWidgets.QApplication.translate("MainWindow", "[null]", None, -1))
        self.pushButton_know.setText(QtWidgets.QApplication.translate("MainWindow", "Know Word", None, -1))
        self.pushButton_dontKnow.setText(QtWidgets.QApplication.translate("MainWindow", "Don\'t Know", None, -1))
        self.checkBox_autoPlay.setText(QtWidgets.QApplication.translate("MainWindow", "Autoplay", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_flashcards), QtWidgets.QApplication.translate("MainWindow", "Flashcards", None, -1))
        self.label_quizWord.setText(QtWidgets.QApplication.translate("MainWindow", "[null]", None, -1))
        self.pushButton_quizChoice1.setText(QtWidgets.QApplication.translate("MainWindow", "[Word1]", None, -1))
        self.pushButton_quizChoice2.setText(QtWidgets.QApplication.translate("MainWindow", "[Word2]", None, -1))
        self.pushButton_quizChoice3.setText(QtWidgets.QApplication.translate("MainWindow", "[Word3]", None, -1))
        self.pushButton_quizChoice4.setText(QtWidgets.QApplication.translate("MainWindow", "[Word4]", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_quiz), QtWidgets.QApplication.translate("MainWindow", "Quiz", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_statistics), QtWidgets.QApplication.translate("MainWindow", "Statistics", None, -1))
        self.menu_file.setTitle(QtWidgets.QApplication.translate("MainWindow", "Fi&le", None, -1))
        self.menu_help.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Help", None, -1))
        self.menuSettings.setTitle(QtWidgets.QApplication.translate("MainWindow", "Settings", None, -1))
        self.menuView.setTitle(QtWidgets.QApplication.translate("MainWindow", "View", None, -1))
        self.menuDeck.setTitle(QtWidgets.QApplication.translate("MainWindow", "Deck", None, -1))
        self.actionFrom_Template.setText(QtWidgets.QApplication.translate("MainWindow", "From Template...", None, -1))
        self.actionQuit.setText(QtWidgets.QApplication.translate("MainWindow", "&Quit", None, -1))
        self.actionOpen.setText(QtWidgets.QApplication.translate("MainWindow", "&Open...", None, -1))
        self.actionTemplate_Data.setText(QtWidgets.QApplication.translate("MainWindow", "&Template Data", None, -1))
        self.actionUser_Data.setText(QtWidgets.QApplication.translate("MainWindow", "&User Data", None, -1))
        self.actionImport_Data.setText(QtWidgets.QApplication.translate("MainWindow", "&Import Data", None, -1))
        self.actionHow_to_play.setText(QtWidgets.QApplication.translate("MainWindow", "How to play", None, -1))
        self.actionUserGuide.setText(QtWidgets.QApplication.translate("MainWindow", "&User Guide", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))
        self.actionDonate.setText(QtWidgets.QApplication.translate("MainWindow", "Donate", None, -1))
        self.actionPreferences.setText(QtWidgets.QApplication.translate("MainWindow", "Preferences...", None, -1))
        self.actionBackup_Database.setText(QtWidgets.QApplication.translate("MainWindow", "Backup Database", None, -1))
        self.actionExport_to_CSV.setText(QtWidgets.QApplication.translate("MainWindow", "Export to CSV...", None, -1))
        self.actionSave_progress.setText(QtWidgets.QApplication.translate("MainWindow", "Save Progress", None, -1))
        self.actionStar_current_word.setText(QtWidgets.QApplication.translate("MainWindow", "Star current word", None, -1))
        self.actionReset_Statistics.setText(QtWidgets.QApplication.translate("MainWindow", "Reset Statistics...", None, -1))
        self.actionRestore_Database.setText(QtWidgets.QApplication.translate("MainWindow", "Restore Database", None, -1))
        self.actionToggle_Pronunciation.setText(QtWidgets.QApplication.translate("MainWindow", "Show Pronunciation", None, -1))
        self.actionImport_from_CSV.setText(QtWidgets.QApplication.translate("MainWindow", "Import from CSV...", None, -1))
        self.actionEdit_deck.setText(QtWidgets.QApplication.translate("MainWindow", "Edit deck", None, -1))
        self.actionAdd_empty_deck.setText(QtWidgets.QApplication.translate("MainWindow", "Add empty deck", None, -1))

