# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Typing.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Typing(object):
    def setupUi(self, Typing):
        Typing.setObjectName("Typing")
        Typing.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(Typing)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 621, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.labelVocab = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK JP")
        font.setPointSize(24)
        self.labelVocab.setFont(font)
        self.labelVocab.setObjectName("labelVocab")
        self.horizontalLayout_2.addWidget(self.labelVocab)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditAnswer = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK JP")
        self.lineEditAnswer.setFont(font)
        self.lineEditAnswer.setText("")
        self.lineEditAnswer.setObjectName("lineEditAnswer")
        self.horizontalLayout.addWidget(self.lineEditAnswer)
        self.pushButtonEnter = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButtonEnter.setAutoDefault(False)
        self.pushButtonEnter.setDefault(True)
        self.pushButtonEnter.setObjectName("pushButtonEnter")
        self.horizontalLayout.addWidget(self.pushButtonEnter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)
        self.labelNumCorrect = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelNumCorrect.setObjectName("labelNumCorrect")
        self.horizontalLayout_3.addWidget(self.labelNumCorrect)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.pushButtonSkip = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButtonSkip.setObjectName("pushButtonSkip")
        self.horizontalLayout_3.addWidget(self.pushButtonSkip)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        Typing.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Typing)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDeck = QtWidgets.QMenu(self.menubar)
        self.menuDeck.setObjectName("menuDeck")
        Typing.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Typing)
        self.statusbar.setObjectName("statusbar")
        Typing.setStatusBar(self.statusbar)
        self.actionShuffle = QtWidgets.QAction(Typing)
        self.actionShuffle.setObjectName("actionShuffle")
        self.actionExit = QtWidgets.QAction(Typing)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menuDeck.addSeparator()
        self.menuDeck.addAction(self.actionShuffle)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDeck.menuAction())

        self.retranslateUi(Typing)
        self.actionExit.triggered.connect(Typing.close)
        self.lineEditAnswer.returnPressed.connect(self.pushButtonEnter.click)
        QtCore.QMetaObject.connectSlotsByName(Typing)

    def retranslateUi(self, Typing):
        _translate = QtCore.QCoreApplication.translate
        Typing.setWindowTitle(_translate("Typing", "MainWindow"))
        self.labelVocab.setText(_translate("Typing", "null"))
        self.lineEditAnswer.setPlaceholderText(_translate("Typing", "Enter your answer"))
        self.pushButtonEnter.setText(_translate("Typing", "Don\'t know"))
        self.labelNumCorrect.setText(_translate("Typing", "0/0"))
        self.pushButtonSkip.setText(_translate("Typing", "Not sure"))
        self.menuFile.setTitle(_translate("Typing", "Fi&le"))
        self.menuDeck.setTitle(_translate("Typing", "&Deck"))
        self.actionShuffle.setText(_translate("Typing", "&Shuffle"))
        self.actionExit.setText(_translate("Typing", "&Exit"))

