# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/DeckNamePrompt.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeckNamePromptDialog(object):
    def setupUi(self, DeckNamePromptDialog):
        DeckNamePromptDialog.setObjectName("DeckNamePromptDialog")
        DeckNamePromptDialog.resize(480, 182)
        DeckNamePromptDialog.setSizeGripEnabled(False)
        DeckNamePromptDialog.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(DeckNamePromptDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_selectStudyLanguages = QtWidgets.QLabel(DeckNamePromptDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_selectStudyLanguages.sizePolicy().hasHeightForWidth())
        self.label_selectStudyLanguages.setSizePolicy(sizePolicy)
        self.label_selectStudyLanguages.setObjectName("label_selectStudyLanguages")
        self.verticalLayout_2.addWidget(self.label_selectStudyLanguages)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_vocabulary = QtWidgets.QLabel(DeckNamePromptDialog)
        self.label_vocabulary.setObjectName("label_vocabulary")
        self.verticalLayout_5.addWidget(self.label_vocabulary)
        self.comboBox_vocabulary = QtWidgets.QComboBox(DeckNamePromptDialog)
        self.comboBox_vocabulary.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_vocabulary.setMaximumSize(QtCore.QSize(225, 16777215))
        self.comboBox_vocabulary.setObjectName("comboBox_vocabulary")
        self.verticalLayout_5.addWidget(self.comboBox_vocabulary)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_definition = QtWidgets.QLabel(DeckNamePromptDialog)
        self.label_definition.setObjectName("label_definition")
        self.verticalLayout_3.addWidget(self.label_definition)
        self.comboBox_definition = QtWidgets.QComboBox(DeckNamePromptDialog)
        self.comboBox_definition.setMaximumSize(QtCore.QSize(225, 16777215))
        self.comboBox_definition.setCurrentText("")
        self.comboBox_definition.setObjectName("comboBox_definition")
        self.verticalLayout_3.addWidget(self.comboBox_definition)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.lineEdit_enterDeckName = QtWidgets.QLineEdit(DeckNamePromptDialog)
        self.lineEdit_enterDeckName.setObjectName("lineEdit_enterDeckName")
        self.verticalLayout_2.addWidget(self.lineEdit_enterDeckName)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(DeckNamePromptDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DeckNamePromptDialog)
        self.buttonBox.accepted.connect(DeckNamePromptDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(DeckNamePromptDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DeckNamePromptDialog)

    def retranslateUi(self, DeckNamePromptDialog):
        _translate = QtCore.QCoreApplication.translate
        DeckNamePromptDialog.setWindowTitle(_translate("DeckNamePromptDialog", "Create a new deck"))
        self.label_selectStudyLanguages.setText(_translate("DeckNamePromptDialog", "Select study languages"))
        self.label_vocabulary.setToolTip(_translate("DeckNamePromptDialog", "Language for the vocabulary words being learned."))
        self.label_vocabulary.setText(_translate("DeckNamePromptDialog", "Vocabulary"))
        self.label_definition.setToolTip(_translate("DeckNamePromptDialog", "Language for the definition of the vocabulary word which the user can easily understand."))
        self.label_definition.setText(_translate("DeckNamePromptDialog", "Definition"))
        self.lineEdit_enterDeckName.setPlaceholderText(_translate("DeckNamePromptDialog", "Enter new deck name here..."))
