# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/GenericDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GenericDialog(object):
    def setupUi(self, GenericDialog):
        GenericDialog.setObjectName("GenericDialog")
        GenericDialog.resize(480, 240)
        GenericDialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(GenericDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(GenericDialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(GenericDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(GenericDialog)
        self.buttonBox.accepted.connect(GenericDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(GenericDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(GenericDialog)

    def retranslateUi(self, GenericDialog):
        _translate = QtCore.QCoreApplication.translate
        GenericDialog.setWindowTitle(_translate("GenericDialog", "Generic Dialog"))
        self.label.setText(_translate("GenericDialog", "TextLabel"))
