# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingsDialog.ui',
# licensing of 'SettingsDialog.ui' applies.
#
# Created: Fri Apr  5 04:22:56 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(475, 505)
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(SettingsDialog)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 459, 440))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_globalSettings = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_globalSettings.sizePolicy().hasHeightForWidth())
        self.label_globalSettings.setSizePolicy(sizePolicy)
        self.label_globalSettings.setTextFormat(QtCore.Qt.PlainText)
        self.label_globalSettings.setAlignment(QtCore.Qt.AlignCenter)
        self.label_globalSettings.setObjectName("label_globalSettings")
        self.verticalLayout_6.addWidget(self.label_globalSettings)
        self.checkBox_shuffle = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_shuffle.sizePolicy().hasHeightForWidth())
        self.checkBox_shuffle.setSizePolicy(sizePolicy)
        self.checkBox_shuffle.setObjectName("checkBox_shuffle")
        self.verticalLayout_6.addWidget(self.checkBox_shuffle)
        self.checkBox_showPronunciation = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_showPronunciation.setObjectName("checkBox_showPronunciation")
        self.verticalLayout_6.addWidget(self.checkBox_showPronunciation)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_displayFirst = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_displayFirst.sizePolicy().hasHeightForWidth())
        self.label_displayFirst.setSizePolicy(sizePolicy)
        self.label_displayFirst.setObjectName("label_displayFirst")
        self.horizontalLayout_3.addWidget(self.label_displayFirst)
        self.radioButton_vocabulary = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_vocabulary.sizePolicy().hasHeightForWidth())
        self.radioButton_vocabulary.setSizePolicy(sizePolicy)
        self.radioButton_vocabulary.setChecked(True)
        self.radioButton_vocabulary.setObjectName("radioButton_vocabulary")
        self.horizontalLayout_3.addWidget(self.radioButton_vocabulary)
        self.radioButton_definition = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_definition.sizePolicy().hasHeightForWidth())
        self.radioButton_definition.setSizePolicy(sizePolicy)
        self.radioButton_definition.setObjectName("radioButton_definition")
        self.horizontalLayout_3.addWidget(self.radioButton_definition)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.label_typingSettings = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_typingSettings.sizePolicy().hasHeightForWidth())
        self.label_typingSettings.setSizePolicy(sizePolicy)
        self.label_typingSettings.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_typingSettings.setAlignment(QtCore.Qt.AlignCenter)
        self.label_typingSettings.setObjectName("label_typingSettings")
        self.verticalLayout_6.addWidget(self.label_typingSettings)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_6.addWidget(self.line_3)
        self.label_flashcardSettings = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_flashcardSettings.sizePolicy().hasHeightForWidth())
        self.label_flashcardSettings.setSizePolicy(sizePolicy)
        self.label_flashcardSettings.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flashcardSettings.setObjectName("label_flashcardSettings")
        self.verticalLayout_6.addWidget(self.label_flashcardSettings)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_6.addWidget(self.line_4)
        self.label_quizSettings = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_quizSettings.sizePolicy().hasHeightForWidth())
        self.label_quizSettings.setSizePolicy(sizePolicy)
        self.label_quizSettings.setAlignment(QtCore.Qt.AlignCenter)
        self.label_quizSettings.setObjectName("label_quizSettings")
        self.verticalLayout_6.addWidget(self.label_quizSettings)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_6.addWidget(self.line_5)
        self.label_miscSettings = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_miscSettings.sizePolicy().hasHeightForWidth())
        self.label_miscSettings.setSizePolicy(sizePolicy)
        self.label_miscSettings.setAlignment(QtCore.Qt.AlignCenter)
        self.label_miscSettings.setObjectName("label_miscSettings")
        self.verticalLayout_6.addWidget(self.label_miscSettings)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.line = QtWidgets.QFrame(SettingsDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setMaximumSize(QtCore.QSize(16777215, 36))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SettingsDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), SettingsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), SettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        SettingsDialog.setWindowTitle(QtWidgets.QApplication.translate("SettingsDialog", "Dialog", None, -1))
        self.label_globalSettings.setText(QtWidgets.QApplication.translate("SettingsDialog", "Global Settings", None, -1))
        self.checkBox_shuffle.setText(QtWidgets.QApplication.translate("SettingsDialog", "Shuffle Order", None, -1))
        self.checkBox_showPronunciation.setText(QtWidgets.QApplication.translate("SettingsDialog", "Show Pronunciation Field", None, -1))
        self.label_displayFirst.setText(QtWidgets.QApplication.translate("SettingsDialog", "Display first:", None, -1))
        self.radioButton_vocabulary.setText(QtWidgets.QApplication.translate("SettingsDialog", "Vocabulary", None, -1))
        self.radioButton_definition.setText(QtWidgets.QApplication.translate("SettingsDialog", "Definition", None, -1))
        self.label_typingSettings.setText(QtWidgets.QApplication.translate("SettingsDialog", "Typing Settings", None, -1))
        self.label_flashcardSettings.setText(QtWidgets.QApplication.translate("SettingsDialog", "Flashcard Settings", None, -1))
        self.label_quizSettings.setText(QtWidgets.QApplication.translate("SettingsDialog", "Quiz Settings", None, -1))
        self.label_miscSettings.setText(QtWidgets.QApplication.translate("SettingsDialog", "Misc Settings", None, -1))

